export const AUTH_ACTION_TYPES = {
  SET_CURRENT_USER: 'auth/SET_CURRENT_USER',
  SET_AUTH_LOADING: 'auth/SET_AUTH_LOADING',
  SET_AUTH_ERROR: 'auth/SET_AUTH_ERROR',
  LOGOUT_USER: 'auth/LOGOUT_USER',
};
