export const FORM_ACTION_TYPES = {
  UPDATE_FIELD: 'form/UPDATE_FIELD',
  SET_ERRORS: 'form/SET_ERRORS',
  CLEAR_ERRORS: 'form/CLEAR_ERRORS',
  START_SUBMIT: 'form/START_SUBMIT',
  STOP_SUBMIT: 'form/STOP_SUBMIT',
  RESET_FORM: 'form/RESET_FORM',
  MARK_DIRTY: 'form/MARK_DIRTY',
};
